### ISSUE TITLE
 Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by tryx78** [kijai/ComfyUI-LivePortraitKJ#31]
Torch not compiled with CUDA enabled

i have a M3 Pro , how can I solve it?

thanks

**Comment by Grant-CP** [comment]
I got it working on my macbook. See this issue: https://github.com/kijai/ComfyUI-LivePortraitKJ/issues/33. Please post an issue with numbers about how quickly it performs on your machine and your machine specs. I'm very curious how fast it goes on an M3 vs an M1

Don't forget to mark your issue as completed if it works.

**Comment by tryx78** [comment]
hi grant, now work wiht new repo
9 second video in 141.06 second 
<img width="293" alt="Screenshot 2024-07-06 alle 22 43 07" src="https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/136930363/5520fe30-ede6-4798-b1cb-09cad62b5979">
